-- =========================================================
-- BASE APPLICATIVE DU PORTAIL OBI
-- =========================================================

-- =========================================================
-- MODULE 1 : SECURITE (comptes du PORTAIL - independants d'OBI)
-- =========================================================
CREATE TABLE UTILISATEUR (
    ID_UTILISATEUR  NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOM             VARCHAR2(100) NOT NULL,
    PRENOM          VARCHAR2(100) NOT NULL,
    EMAIL           VARCHAR2(150) UNIQUE NOT NULL,
    MOT_DE_PASSE    VARCHAR2(255) NOT NULL,
    ACTIF           NUMBER(1) DEFAULT 1 CHECK (ACTIF IN (0,1)),
    DATE_CREATION   DATE DEFAULT SYSDATE
);

CREATE TABLE ROLE (
    ID_ROLE      NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOM_ROLE     VARCHAR2(50) NOT NULL,
    DESCRIPTION  VARCHAR2(255)
);

CREATE TABLE UTILISATEUR_ROLE (
    ID_UTILISATEUR NUMBER REFERENCES UTILISATEUR(ID_UTILISATEUR),
    ID_ROLE         NUMBER REFERENCES ROLE(ID_ROLE),
    PRIMARY KEY (ID_UTILISATEUR, ID_ROLE)
);

CREATE TABLE PERMISSION (
    ID_PERMISSION   NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOM_PERMISSION  VARCHAR2(100) NOT NULL,
    DESCRIPTION     VARCHAR2(255)
);

CREATE TABLE ROLE_PERMISSION (
    ID_ROLE       NUMBER REFERENCES ROLE(ID_ROLE),
    ID_PERMISSION NUMBER REFERENCES PERMISSION(ID_PERMISSION),
    PRIMARY KEY (ID_ROLE, ID_PERMISSION)
);

CREATE TABLE SESSION_UTILISATEUR (
    ID_SESSION      VARCHAR2(255) PRIMARY KEY,
    ID_UTILISATEUR  NUMBER REFERENCES UTILISATEUR(ID_UTILISATEUR),
    DATE_DEBUT      DATE DEFAULT SYSDATE,
    DATE_FIN        DATE,
    STATUT          VARCHAR2(20) DEFAULT 'ACTIVE'
);

-- =========================================================
-- MODULE 2 : CATALOGUE DES RAPPORTS (metadonnees uniquement)
-- =========================================================
CREATE TABLE CATEGORIE (
    ID_CATEGORIE   NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOM_CATEGORIE  VARCHAR2(100) NOT NULL,
    DESCRIPTION    VARCHAR2(255)
);

CREATE TABLE RAPPORT (
    ID_RAPPORT             NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TITRE                  VARCHAR2(200) NOT NULL,
    DESCRIPTION            VARCHAR2(500),
    ID_CATEGORIE           NUMBER REFERENCES CATEGORIE(ID_CATEGORIE),
    CHEMIN_CATALOGUE_OBI   VARCHAR2(500) NOT NULL,
    TEMPLATE_OBI           VARCHAR2(100),
    FORMATS_DISPO          VARCHAR2(50) DEFAULT 'pdf,xlsx,rtf',
    DATE_CREATION          DATE DEFAULT SYSDATE,
    STATUT                 VARCHAR2(20) DEFAULT 'ACTIF'
);

CREATE TABLE PARAMETRE_RAPPORT (
    ID_PARAMETRE     NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_RAPPORT       NUMBER REFERENCES RAPPORT(ID_RAPPORT),
    NOM_PARAM_OBI    VARCHAR2(100) NOT NULL,
    LIBELLE_AFFICHE  VARCHAR2(150) NOT NULL,
    TYPE             VARCHAR2(20) NOT NULL, -- DATE, TEXTE, LISTE, NOMBRE
    OBLIGATOIRE      NUMBER(1) DEFAULT 0,
    VALEURS_LISTE    VARCHAR2(500)
);

-- =========================================================
-- MODULE 4 : TRACABILITE
-- =========================================================
CREATE TABLE HISTORIQUE_CONSULTATION (
    ID_HISTORIQUE      NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_UTILISATEUR     NUMBER REFERENCES UTILISATEUR(ID_UTILISATEUR),
    ID_RAPPORT         NUMBER REFERENCES RAPPORT(ID_RAPPORT),
    DATE_CONSULTATION  DATE DEFAULT SYSDATE,
    ACTION             VARCHAR2(50),
    FORMAT_EXPORT      VARCHAR2(20),
    DUREE_MS           NUMBER
);

CREATE TABLE JOURNAL_ACTIVITE (
    ID_JOURNAL    NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_UTILISATEUR NUMBER REFERENCES UTILISATEUR(ID_UTILISATEUR),
    DATE_ACTION   DATE DEFAULT SYSDATE,
    ACTION        VARCHAR2(200),
    ADRESSE_IP    VARCHAR2(50)
);
